name: Playwright TypeScript Tests
on:
  push:
    branch: [ main ]
jobs:
  playwright-test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.29.1-focal
      env:
        ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
        ADMIN_PASSWORD: ${{ secrets.ADMINPASSWORD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Start shopping store application
        run: |
          chmod +x ./shopping-store-linux-amd64
          ./shopping-store-linux-amd64 &
      - name: Install dependencies from lockfile
        run: npm ci
      - name: Run playwright tests
        run: npm run test:ci